import jsPDF from "jspdf";

export const getGeneratedBy = async (): Promise<string> => {
  try {
    const token = localStorage.getItem("token");
    console.log(token);

    const res = await fetch("http://localhost:5000/api/users/me", {
      headers: {
        Authorization: `Bearer ${token}`,
      },
    });
    console.log("STATUS:", res.status);

    if (!res.ok) {
      return "Unknown User";
    }

    const data = await res.json();

    return `${data.username || "Unknown"} | ${data.email || "N/A"}`;
  } catch (error) {
    console.error(error);
    return "Unknown User";
  }
};

export const formatFileDateTime = (d: Date) => {
  const pad = (n: number) => String(n).padStart(2, "0");

  return (
    d.getFullYear() +
    "-" +
    pad(d.getMonth() + 1) +
    "-" +
    pad(d.getDate()) +
    "_" +
    pad(d.getHours()) +
    "-" +
    pad(d.getMinutes()) +
    "-" +
    pad(d.getSeconds())
  );
};


export const addHeaderAndFooter = (
  doc: jsPDF,
  systemName: string,
  generatedBy: string,
  pageCount: number,
  pageNumber: number
) => {
  const pageWidth = doc.internal.pageSize.width;
  const pageHeight = doc.internal.pageSize.height;

  const footerY = pageHeight - 10;
  const lineY = pageHeight - 14;
  const systemTextY = pageHeight - 20;

  // HEADER
  doc.setFontSize(10);
  doc.setFont("helvetica");
  doc.text(systemName, 14, 15);

  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.3);
  doc.line(14, 22, pageWidth - 14, 22);

  // FOOTER
  doc.setFontSize(9);

  doc.text(
    "This document is system-generated and intended for internal use only.",
    pageWidth / 2,
    systemTextY,
    { align: "center" }
  );

  doc.line(14, lineY, pageWidth - 14, lineY);

  doc.text(`Generated By: ${generatedBy}`, 9, footerY);

  doc.text(`Page ${pageNumber} of ${pageCount}`, pageWidth / 2, footerY, {
    align: "center",
  });

  doc.text(
    `Generated On: ${formatFileDateTime(new Date())}`,
    pageWidth - 9,
    footerY,
    { align: "right" }
  );
};

export const addPageNumbers = (doc: jsPDF) => {
  const pageCount = doc.getNumberOfPages();

  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);

    const pageWidth = doc.internal.pageSize.width;
    const footerY = doc.internal.pageSize.height - 10;

    doc.setFontSize(9);
    doc.text(`Page ${i} of ${pageCount}`, pageWidth / 2, footerY, {
      align: "center",
    });
  }
};

export const formatRole = (role: string) => {
  return role
    .split("_")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
};
