import jsPDF from "jspdf";

export const getGeneratedBy = async (): Promise<string> => {
  try {
    const token = localStorage.getItem("token");
    console.log(token);

    const res = await fetch("http://localhost:5000/api/users/me", {
      headers: {
        Authorization: `Bearer ${token}`,
      },
    });
    console.log("STATUS:", res.status);

    if (!res.ok) {
      return "Unknown User";
    }

    const data = await res.json();

    return `${data.username || "Unknown"} | ${data.email || "N/A"}`;
  } catch (error) {
    console.error(error);
    return "Unknown User";
  }
};

// ✅ MUST be OUTSIDE the function
export const addFooter = (
  doc: jsPDF,
  generatedBy: string,
  generatedAt: Date
) => {
  const pageWidth = doc.internal.pageSize.width;
  const pageHeight = doc.internal.pageSize.height;

  const footerY = pageHeight - 10;
  const lineY = pageHeight - 14;
  const systemTextY = pageHeight - 20;

  const pageNumber = doc.getCurrentPageInfo().pageNumber;

  const pad = (n: number) => String(n).padStart(2, "0");

  // format date: YYYY-MM-DD HH-MM-SS
  const date =
    generatedAt.getFullYear() +
    "-" +
    pad(generatedAt.getMonth() + 1) +
    "-" +
    pad(generatedAt.getDate());

  const time =
    pad(generatedAt.getHours()) +
    "-" +
    pad(generatedAt.getMinutes()) +
    "-" +
    pad(generatedAt.getSeconds());

  const formattedDateTime = `${date} ${time}`;

  doc.setFontSize(9);

  // System message
  doc.text(
    "This document is system-generated and intended for internal use only.",
    pageWidth / 2,
    systemTextY,
    { align: "center" }
  );

  // separator line
  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.3);
  doc.line(14, lineY, pageWidth - 14, lineY);

  // footer content
  doc.text(`Generated By: ${generatedBy}`, 9, footerY);

  doc.text(`Page ${pageNumber}`, pageWidth / 2, footerY, {
    align: "center",
  });

  doc.text(`Generated On: ${formattedDateTime}`, pageWidth - 9, footerY, {
    align: "right",
  });
};

export const addHeader = (doc: jsPDF, systemName: string) => {
  // System name (top-left)
  doc.setFontSize(10);
  doc.setFont("helvetica");
  doc.text(systemName, 14, 15);

  // Separator line
  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.3);
  doc.line(14, 22, doc.internal.pageSize.width - 14, 22);
};

export const formatFileDateTime = (d: Date) => {
  const pad = (n: number) => String(n).padStart(2, "0");

  return (
    d.getFullYear() +
    "-" +
    pad(d.getMonth() + 1) +
    "-" +
    pad(d.getDate()) +
    "_" +
    pad(d.getHours()) +
    "-" +
    pad(d.getMinutes()) +
    "-" +
    pad(d.getSeconds())
  );
};
